### ISSUE TITLE
Example issue - Create enter button for name field.

### ISSUE THREAD

**Issue by soulclimberchick** [marrob01/Product-Club-Team-5#2]
This first task requires  input from Marcus into this issue. Add details of steps to be done and  any dependencies needed by other teams or individuals.

Button must be rectangular with round corners. Must actuate a "success" prompt alerting the user that the action was successful.

**Comment by soulclimberchick** [comment]
Created buttons for ....  they result in ..... and passed all tests.

**Comment by marrob01** [comment]
MAybe I will
